### ISSUE TITLE
Ordnerstruktur und Bennenung der Controller

### ISSUE THREAD

**Issue by abergy** [FHBielefeld-IFM-WS1718-SWEng1/iOSApp#7]
- Ordner Struktur ändern ?
- Objektordner ?
- Sinnvolle umbenennen der Controller ?

**Comment by abergy** [comment]
Vorschlag von mir

- ViewController = OverviewController
- Ein großer Objektordner /Objects in dem dann /User /Event etc sind 
- In den Ordner /ViewController kommen alle ViewController

Vorschlag von @dleunig 

- In den Ordner /ViewController kommen alle ViewController und wenn, wie bei Events, noch Objecte zu dem Controller existieren kommen die im Ordner /ViewController in einen gemeinsamen Unterordner /Events

**Comment by jmueller19** [comment]
Ich bin für einen großen Objektordner
